spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://dev-rds-instance.ckjf4dnmuwog.ap-northeast-2.rds.amazonaws.com/calocheck__dev?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci
    username: user
    password: calocheck17
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  security:
    csrf:
      enabled: true
    oauth2:
      client:
        registration:
          kakao:
            scope: account_email, gender
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
          naver:
            scope:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  test:
    exclude: '**/*Tests.class'
