recommend:
  food-list:
    #탄수화물
    carbohydrate: 국수, 빵, 라면, 떡, 사과, 현미, 커피, 과자, 고구마, 보리
    #단백질
    protein: 돼지고기, 닭고기, 소고기, 달걀, 우유, 국수, 두부, 빵, 대두, 오징어
    #지방
    fat: 돼지고기, 소고기, 콩기름, 달걀, 우유, 라면, 마요네즈, 빵, 과자, 닭고기
    #칼슘
    calcium: 우유, 김치, 라면, 멸치, 요구르트, 달걀, 치즈, 두부, 커피, 미역, 미꾸라지
    #나트륨
    sodium: 소금, 김치, 간장, 된장, 고추장, 라면, 국수, 빵, 쌈장, 미역, 달걀
    #칼륨
    potassium: 돼지고기, 김치, 우유, 닭고기, 커피, 감자, 고구마, 소고기, 고춧가루, 사과
    #비타민 A
    vitaminA: 당근, 달걀, 시금치, 우유, 상추, 고추장, 김, 수박, 시리얼, 장어
    #비타민 C
    vitaminC: 귤, 딸기, 오렌지, 시금치, 무, 토마토, 고구마, 풋고추, 시리얼, 양배추
    #고단백&저지방 육류
    meat: 닭 가슴살, 닭 안심살, 소 우둔살, 소 홍두깨살, 소 사태살, 돼지 등심살, 돼지 안심살, 돼지 앞다리살
    #GI지수 높은 음식
    highGI: 찐 감자, 군 고구마, 식빵, 찐 옥수수, 찐 고구마, 당면, 메밀면, 모닝빵
    #GI지수 낮은 음식
    lowGI: 군밤, 쌀국수, 찐 단호박, 시리얼, 소면, 칼국수, 보리밥
  description:
    carbohydrate: 에너지와 힘을 내는 가장 기본적인 영양소로, 음식에 단맛을 제공합니다. 주로 곡식종류, 빵류, 면류, 감자, 고구마류, 설탕류, 과일류 음식에 많이 함유되어 있습니다.
    protein: 우리 몸을 이루고 있는 체조직의 성장과 유지 작용을 하는 요소로, 주로 고기, 생선, 조개류, 알류, 콩류, 우유 및 유제품에 많이 함유되어 있으며, 부족할 경우 성장지연, 질병에 대한 저항력 감소, 빈혈과 같은 문제가 발생할 수 있습니다.
    fat: 에너지와 힘을 내는 영양소로, 농축된 에너지의 급원체지방을 축적하여 체온의 손실을 막고 체내의 장기를 보호하는 역할을 합니다. 주로 참기름, 들기름, 콩기름, 마요네즈, 쇠기름, 돼지기름, 버터, 마가린 등에 많이 함유되어 있으며, 과할 경우 과비만, 동맥경화, 고혈압 등 성인병을 유발할 수 있습니다.
    calcium: 골격과 치아의 구성 성분이며, 혈액의 응고를 촉진시키는 등의 역할을 하는 영양소 입니다. 주로 우유 및 유제품, 뼈째먹는 생선, 굴 및 해조류, 푸른잎 채소, 콩, 계란 등에 많이 함유되어 있으며, 부족할 경우 골다공증 발생 위험이 증가할 수 있습니다.
    sodium: 몸의 삼투압을 조절하고 체내 수분 균형을 유지하는 전해질로써, 음식이나 소금을 통해 나트륨을 섭취할 수 있습니다. 섭취된 나트륨은 신체에서 필요한 만큼 사용하고 신장에서 나머지를 배출하게 되며, 신장 기능이 저하되면 나트륨 농도도 변해 탈수나 부종이 발생할 수 있습니다.
    potassium: 신경의 흥분이나 심근의 수축을 돕는 역할을 하는 전해질로써, 혈액 내 칼륨 수치가 너무 높거나 낮아지면 부정맥, 호흡곤란, 쇼크가 발생할 수 있어 주의가 필요합니다. 칼륨 수치가 낮으면 전신 경련, 의식 저하, 근무력증 등의 증상이 발생할 수 있습니다.
    vitaminA: 어두운 곳에서 눈의 적응, 피부 점막의 건강 유지, 성장촉진, 골격과 치아의 구성성분 이기도 하며, 혈액의 응고를 촉진시키는 등의 역할을 하는 영양소 입니다. 주로 동물성 식품중에 간유, 난황, 버터, 연어에 포함되어 있고, 식물성 식품중에서는 당근, 시금치 등의 녹황색 채소, 감, 귤 등의 과일등에 포함되어 있습니다. 부족할 경우 야맹증, 피부의 거칠음, 각막 건조증을 유발할 수 있습니다.
    vitaminC: 피부, 뼈, 혈관 등을 건강하게 유지하고, 세포의 산화, 환원에 관여하기도 하며, 혈액을 응고시키는 역할을 하는 영양소 입니다. 주로 감귤류, 녹황색 채소 등 싱싱한 채소와 과일에 풍부하게 함유되어있고, 부족할 경우 괴혈병(잇몸 출혈, 빈혈)이 발생할 수 있습니다.
    meat: 단백질은 풍부하고, 지방은 적은 육류 부위들을 소개해 드릴게요!
    highGI: GI지수란, 음식을 섭취한 후 얼마나 혈당을 빨리 상승시키는지를 측정해 숫자로 나타낸 것을 의미합니다. GI 지수가 높은 음식을 먹게 되면 급격한 혈당 상승으로 인슐린 분비가 유발되고, 폭식을 유발하게 됩니다.
    lowGI: GI지수란, 음식을 섭취한 후 얼마나 혈당을 빨리 상승시키는지를 측정해 숫자로 나타낸 것을 의미합니다. GI 지수가 높은 음식을 먹게 되면 급격한 혈당 상승으로 인슐린 분비가 유발되고, 폭식을 유발하게 됩니다.
  recommend-list: 탄수화물, 단백질, 지방, 칼슘, 나트륨, 칼륨, 비타민A, 비타민C, 고단백&저지방 육류, GI지수 높은 음식, GI지수 낮은 음식
  setting-list: carbohydrate, protein, fat, calcium, sodium, potassium,vitaminA, vitaminC, meat, highGI, lowGI