spring:
  profiles:
    active: dev
    include: secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/calocheck__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
          naver:
            scope:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  recommendList:
    #탄수화물
    carbohydrate: 국수, 빵, 라면, 떡, 사과, 현미, 커피, 과자, 고구마, 보리
    #단백질
    protein: 돼지고기, 닭고기, 소고기, 달걀, 우유, 국수, 두부, 빵, 대두, 오징어
    #지방
    fat: 돼지고기, 소고기, 콩기름, 달걀, 우유, 라면, 마요네즈, 빵, 과자, 닭고기
    #칼슘
    calcium: 우유, 김치, 라면, 멸치, 요구르트, 달걀, 치즈, 두부, 커피, 미역, 미꾸라지
    #나트륨
    sodium: 소금, 김치, 간장, 된장, 고추장, 라면, 국수, 빵, 쌈장, 미역, 달걀
    #칼륨
    potassium: 돼지고기, 김치, 우유, 닭고기, 커피, 감자, 고구마, 소고기, 고춧가루, 사과
    #비타민 A
    vitaminA: 당근, 달걀, 시금치, 우유, 상추, 고추장, 김, 수박, 시리얼, 장어
    #비타민 C
    vitaminC: 귤, 딸기, 오렌지, 시금치, 무, 토마토, 고구마, 풋고추, 시리얼, 양배추

  description:
    carbohydrate: 에너지와 힘을 내는 가장 기본적인 영양소, 음식에 단맛을 제공,\n 함유 식품 => 곡식종류, 빵류, 면류, 감자, 고구마류, 설탕류, 과일류
    protein: 우리 몸을 이루고 있는 체조직의 성장과 유지 작용 \n 함유식품 => 고기, 생선, 조개류, 알류, 콩류, 우유 및 유제품 \n 결핍증 ① 성장지연 ② 질병에 대한 저항력 감소 ③ 빈혈
    fat: 에너지와 힘을 내는 영양소로 농축된 에너지의 급원체지방을 축적하여 체온의 손실을 막고 체내의 장기를 보호 \n 함유식품 => 참기름, 들기름, 콩기름, 마요네즈, 쇠기름, 돼지기름, 버터, 마가린 \n 과잉증 => 비만, 동맥경화, 고혈압 등 성인병 유발
    calcium: 골격과 치아의 구성 성분 혈액의 응고 촉진 \n 함유식품 => 우유 및 유제품, 뼈째먹는 생선, 굴 및 해조류, 푸른잎 채소, 콩, 계란 \n 결핍증 => 골다공증 발생 위험 증가, 우리 몸을 이루고 있는 체조직의 성장과 유지작용
    sodium: 몸의 삼투압을 조절하고 체내 수분 균형을 유지하는 전해질 \n 음식이나 소금을 통해 나트륨을 섭취 \n 섭취된 나트륨을 신체에서 필요한 만큼 사용하고 신장에서 나머지를 배출 \n 신장 기능이 저하되면 나트륨 농도도 변해 탈수나 부종이 발생할 수 있음.
    potassium: 신경의 흥분이나 심근의 수축을 돕는 역할을 하는 전해질 \n 혈액 내 칼륨 수치가 너무 높거나 낮아지면 부정맥, 호흡곤란, 쇼크가 발생할 수 있어 주의 \n 칼륨 수치가 낮으면 전신 경련, 의식 저하, 근무력증 증상이 발생할 수 있음.
    vitaminA: 어두운 곳에서 눈의 적응, 피부 점막의 건강 유지, 성장촉진 골격과 치아의 구성성분혈액의 응고 촉진 \n 함유식품 \n 동물성 식품 => 간유, 난황, 버터, 연어 \n 식물성 식품 => 당근, 시금치 등의 녹황색 채소, 감, 귤 등의 과일 \n 결핍증 => 야맹증, 피부의 거칠음, 각막 건조증
    vitaminC: 피부, 뼈, 혈관 등을 건강하게 유지, 세포의 산화, 환원에 관여, 혈액응고 \n 함유식품 => 감귤류, 녹황색 채소 등 싱싱한 채소와 과일 \n 결핍증 => 괴혈병(잇몸 출혈, 빈혈)

cloud:
  aws:
    credentials:
      access-key: prhWvIq8wc81j6w0Msa6
      secret-key: gL5XFH4GQbg3SOczdgaH3W8kr3N3UxKncCNp2gmn
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: calocheck
  cdn:
    url: https://mxpijmgqueja17962851.cdn.ntruss.com/
